# Generated by Django 3.1.3 on 2021-02-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postCategory', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('shortDescription', models.CharField(max_length=300)),
            ],
        ),
    ]
