# Generated by Django 3.1.3 on 2021-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thubnail',
            field=models.ImageField(blank=True, default='', height_field=284, upload_to=None, width_field=400),
        ),
    ]
