# Generated by Django 3.1.3 on 2021-02-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_post_thubnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thubnail',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
