# Generated by Django 3.1.3 on 2021-02-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_auto_20210221_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDrafts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=50)),
                ('draftLink', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
