# Generated by Django 3.1.3 on 2021-02-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_postdrafts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostDrafts',
            new_name='PostDraft',
        ),
    ]
